### ISSUE TITLE
Where are '?' and '!'?

### ISSUE THREAD

**Issue by NUPLID** [jcrowgey/neolo#4] opened 2019-03-27 03:10 UTC
I found a bug yesterday that seems a serious problem. In the 'Wordtypes and frequencies (unigram model):' I cannot find '?' and '!' and thus 'the sentences in your text.', 'Average sentence length:' and 
'Punctuation ratio:' results come wrong. To check the error follow
https://drive.google.com/file/d/1LQRNF4kTVk8AyebYf4Hj1KJZDsaaPbJJ/view

In this address one may find other results to check:

https://agrippaproject.wordpress.com/
Thanks

**Comment by jcrowgey** [comment] 2019-03-27 04:34
I think I may need more help to reproduce this.  I created the file `mary.txt`:

```shell
$ cat mary.txt
Mary had a little lamb,
Her fleece was white as snow!
Everywhere that mary went,
the lamb was sure to go?
```

When I run `neolo` (using neolo 0.1.0) on this file with `-t` (wordtypes):

```shell
$ neolo mary.txt -t

Statistics:
-----------
Text size: 25 tokens in 21 types.
Number of hapax legomena: 17
TTR (type-token ratio): 0.84
HTR (hapax-token ratio): 0.68
HTyR (hapax-type ratio): 0.8095238095238095

Wordtypes and frequencies (unigram model):
------------------------------------------
(Rank,Count,Wordform)
---------------------
1 2 ,
2 2 lamb
3 2 mary
4 2 was
5 1 !
6 1 ?
7 1 a
8 1 as
9 1 everywhere
10 1 fleece
11 1 go
12 1 had
13 1 her
14 1 little
15 1 snow
16 1 sure
17 1 that
18 1 the
19 1 to
20 1 went
21 1 white
```

That list includes '?' and '!'.

**Comment by NUPLID** [comment] 2019-03-29 01:38
Hi, Joshua! What kind of information should I supply? I still running Neolo and the two marks are still absent of the Wordtypes and frenquencies list. Sorry for the delay, busy time.

**Comment by NUPLID** [comment] 2019-03-29 04:12
Joshua, I am leaving a sample of the text I have been working with in the tentative to format it in a way I can get the right counting of '.', '?' and '!' and the calculations done well.

" —For this, O dearly beloved, is the genuine Christine: body and soul
and blood and ouns. Slow music, please. Shut your eyes, gents. One
moment. A little trouble about those white corpuscles. Silence, all.

He peered sideways up and gave a long slow whistle of call, then paused
awhile in rapt attention, his even white teeth glistening here and
there with gold points. Chrysostomos. Two strong shrill whistles
answered through the calm.

—Thanks, old chap, he cried briskly. That will do nicely. Switch off
the current, will you?

He skipped off the gunrest and looked gravely at his watcher, gathering
about his legs the loose folds of his gown. The plump shadowed face and
sullen oval jowl recalled a prelate, patron of arts in the middle ages.
A pleasant smile broke quietly over his lips.

—The mockery of it! he said gaily. Your absurd name, an ancient Greek!

He pointed his finger in friendly jest and went over to the parapet,
laughing to himself. Stephen Dedalus stepped up, followed him wearily
halfway and sat down on the edge of the gunrest, watching him still as
he propped his mirror on the parapet, dipped the brush in the bowl and
lathered cheeks and neck.

Buck Mulligan’s gay voice went on.

—My name is absurd too: Malachi Mulligan, two dactyls. But it has a
Hellenic ring, hasn’t it? Tripping and sunny like the buck himself. We
must go to Athens. Will you come if I can get the aunt to fork out
twenty quid?

He laid the brush aside and, laughing with delight, cried:

—Will he come? The jejune jesuit!

Ceasing, he began to shave with care.

—Tell me, Mulligan, Stephen said quietly.

—Yes, my love?

—How long is Haines going to stay in this tower?

Buck Mulligan showed a shaven cheek over his right shoulder.

—God, isn’t he dreadful? he said frankly. A ponderous Saxon. He thinks
you’re not a gentleman. God, these bloody English! Bursting with money
and indigestion. Because he comes from Oxford. You know, Dedalus, you
have the real Oxford manner. He can’t make you out. O, my name for you
is the best: Kinch, the knife-blade. "

**Comment by NUPLID** [comment] 2019-03-30 01:46
You can count on me. But I am not of much help.

tks

saulo

Em qua, 27 de mar de 2019 às 01:34, Joshua Crowgey <notifications@github.com>
escreveu:

**Comment by jcrowgey** [comment] 2019-03-30 03:14
Hi Saulo,

Thanks for the sample text, maybe there's some particular configuration of settings or dictionary files that causes the issue that you're reporting.  I say that because when I save your sample text as "sample.txt" and run neolo on it with only `-t` to print the unigram model, I see the "?" and "!" in the output (8th and 13th, respectively):

```shell
~$ neolo -t sample.txt 

Statistics:
-----------
Text size: 439 tokens in 241 types.
Number of hapax legomena: 191
TTR (type-token ratio): 0.5489749430523918
HTR (hapax-token ratio): 0.43507972665148065
HTyR (hapax-type ratio): 0.7925311203319502

Wordtypes and frequencies (unigram model):
------------------------------------------
(Rank,Count,Wordform)
---------------------
1 32 .
2 31 ,
3 20 the
4 14 and
5 14 he
6 8 a
7 8 his
8 7 ?
9 6 to
10 6 you
11 5 in
12 5 of
13 4 !
14 4 :
```

What is the invocation you're using which I can use to reproduce your issue?

**Comment by NUPLID** [comment] 2019-03-30 06:01
Hi Joshua! Things happen very differently when I run the same sample. 

This is the command:

./neolo texts1/4Sample.txt --mltd --msttr -w -p -v -x -a -t --dicts dicio/Web
ster8.txt listas/englist8.txt nomes/20names.txt -s abbrev/eng.txt> ~/Desktop
/4SampleR2.txt

As a result:

"15 sentences in your text.
Average sentence length: 21.466666666666665 tokens.
...
Statistics:
-----------
Text size: 322 tokens in 194 types.
Number of hapax legomena: 156
TTR (type-token ratio): 0.6024844720496895
HTR (hapax-token ratio): 0.484472049689441
HTyR (hapax-type ratio): 0.8041237113402062
Neologisms:  14 types not found in 3 dictionaries
Dictionaries contained 7298227 tokens in 361721 types.
MSTTR...0.8025
MLTD...107.33333333333333 
...
Wordtypes and frequencies (unigram model):
------------------------------------------
(Rank,Count,Wordform)
---------------------
1 24 ,
2 17 the
3 15 .
4 13 and
5 10 he
6 8 his
7 6 to
8 5 a
9 5 in
10 5 of
11 3 over
12 3 with
13 2 :
14 2 about
15 2 brush
16 2 buck
17 2 come
18 2 cried
19 2 gunrest"

**Comment by jcrowgey** [comment] 2019-03-30 17:13
Thanks for the further information, Saulo.  tried again with an invocation similar to the one you reported,  but I wasn't able to reproduce your issue:

```
$ neolo -t ~/sample.txt --mltd --msttr -p -v -x -a   > out
$ grep -E '[?!]' out
8 7 ?
13 4 !
```

As you see, "?" and "!" appear in the unigram model.  I will contact you via email to acquire the rest of the files you are using in order to try again to reproduce using the exact same data you are using.  At this point, I think we can say that the issue must be related to the particular dict and or abbrev files you're using.

**Comment by jcrowgey** [comment] 2019-04-03 04:55
The issue is in regards to an interaction between the `-s` and `-t` options.  Here is a minimal reproduction using the file `mary.txt` above:

```
$ neolo ~/src/neolo/mary.txt -v -t

Statistics:
-----------
Text size: 25 tokens in 21 types.
Number of hapax legomena: 17
TTR (type-token ratio): 0.84
HTR (hapax-token ratio): 0.68
HTyR (hapax-type ratio): 0.8095238095238095

Wordtypes and frequencies (unigram model):
------------------------------------------
(Rank,Count,Wordform)
---------------------
1 2 ,
2 2 lamb
3 2 mary
4 2 was
5 1 !
6 1 ?
7 1 a
8 1 as
9 1 everywhere
10 1 fleece
11 1 go
12 1 had
13 1 her
14 1 little
15 1 snow
16 1 sure
17 1 that
18 1 the
19 1 to
20 1 went
21 1 white
$ neolo ~/src/neolo/mary.txt -v -t -s
2 sentences in your text.
Average sentence length: 11.5 tokens.

Statistics:
-----------
Text size: 23 tokens in 19 types.
Number of hapax legomena: 15
TTR (type-token ratio): 0.8260869565217391
HTR (hapax-token ratio): 0.6521739130434783
HTyR (hapax-type ratio): 0.7894736842105263

Wordtypes and frequencies (unigram model):
------------------------------------------
(Rank,Count,Wordform)
---------------------
1 2 ,
2 2 lamb
3 2 mary
4 2 was
5 1 a
6 1 as
7 1 everywhere
8 1 fleece
9 1 go
10 1 had
11 1 her
12 1 little
13 1 snow
14 1 sure
15 1 that
16 1 the
17 1 to
18 1 went
19 1 white
```

The `-s` option splits the text into sentences based on the sentence-splitting punctuation symbols which are defined in the current version of the program as "." "?" and "!" (you'll notice that "." is also missing from the unigram model when you run with -s).

If we want to preserve the sentence splitting symbols as part of the sentence even when running with `-s`, I can make a patch which will do this.  However, as you note, this means you'll get different numbers if you rerun the patched version of `neolo` against your old texts.

I'll submit a fix for this shortly.  I'll take advantage of this to provide the project with a few tests, starting with a regression test based on this bug.

**Closed as completed** 2019-04-21 04:07 UTC
